"""alter machine, machine log, and create products 2

Revision ID: 2e750739da08
Revises: 91b13a5159a8
Create Date: 2025-11-10 14:27:36.430913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e750739da08'
down_revision: Union[str, Sequence[str], None] = '91b13a5159a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=10), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productions_id'), 'productions', ['id'], unique=False)
    op.create_index(op.f('ix_productions_product_code'), 'productions', ['product_code'], unique=True)
    op.create_table('machine_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('process_temperature', sa.Float(), nullable=True),
    sa.Column('rotational_speed', sa.Integer(), nullable=True),
    sa.Column('torque', sa.Float(), nullable=True),
    sa.Column('tool_wear', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_logs_id'), 'machine_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_logs_id'), table_name='machine_logs')
    op.drop_table('machine_logs')
    op.drop_index(op.f('ix_productions_product_code'), table_name='productions')
    op.drop_index(op.f('ix_productions_id'), table_name='productions')
    op.drop_table('productions')
    # ### end Alembic commands ###
