"""create machines and machine_logs

Revision ID: 580c1caa953d
Revises: 
Create Date: 2025-11-10 13:51:11.079741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580c1caa953d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_table('machine_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('process_temperature', sa.Float(), nullable=True),
    sa.Column('rotational_speed', sa.Integer(), nullable=True),
    sa.Column('torque', sa.Float(), nullable=True),
    sa.Column('tool_wear', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_logs_id'), 'machine_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_logs_id'), table_name='machine_logs')
    op.drop_table('machine_logs')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
